#pragma once

#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE


#define TAPPING_TERM 200
#define PERMISSIVE_HOLD

#define DEFAULT_LAYER_STATE 1

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

